base_config: configs/base/base.yaml
model_type: supervised
model_name: supervised_5

data_args:
  path: data/sleep_eeg/processed/healthy
  mode: subseq
  input_dims: 1
  subseq_size: 1000
  train_stride: 250
  val_stride: 1000
  downsample_factor: 3
  include_channels: [0]
  num_classes: 5
  p_train: 0.05
  p_val: 1

training_args:
  epochs: 100
  batch_size: 64
  eval_batch_size: 64
  lr: 0.001
  save_every_n: 100
