base_config: configs/base/transfer_pretrain_base.yaml
model_type: dsvae

data_args:
  path: data/sleep_eeg/processed/healthy
  mode: fullts
  input_dims: 1
  subseq_size: 200
  train_stride: 200
  val_stride: 200
  include_channels: [0]
  p_train: 0.1
  p_val: 0.1

model_args:
  z_dim: 64
  v_dim: 64
  activation: 'tanh'
  dense_x: []
  dim_RNN_gv: 320
  num_RNN_gv: 4
  dense_gv_v: []
  dense_xv_gxv: []
  dim_RNN_gxv: 64
  num_RNN_gxv: 1
  dense_gxv_gz: []
  dim_RNN_gz: 64
  dim_RNN_prior: 16
  num_RNN_prior: 1
  num_RNN_gz: 1
  dense_vz_x: [64,64]
  dropout_p: 0
  beta: 1
  kl_weight: 1e-5

training_args:
  epochs: 100
  batch_size: 64
  eval_batch_size: 64
  lr: 0.0001
  save_every_n: 100
