base_config: configs/base/lfads_base.yaml
model_type: lfads
data_args:
  path: data/sleep_eeg/processed/healthy
  mode: fullts
  input_dims: 1
  subseq_size: 200
  train_stride: 200
  val_stride: 200
  include_channels: [0]
  p_train: 0.1
  p_val: 0.1

training_args:
  batch_size: 128
  epochs: 100
  eval_every_n: 2
  lr: 0.0001
