base_config: configs/base/base.yaml
model_type: supervised
model_name: supervised_1

data_args:
  path: data/ecg/processed
  mode: subseq
  input_dims: 2
  subseq_size: 500
  downsample_factor: 5
  p_train: 0.01
  p_val: 1
  num_classes: 2

training_args:
  epochs: 100
  batch_size: 64
  eval_batch_size: 64
  lr: 0.001
  save_every_n: 100
